export const topics = [
 {id:'numbers',name:'Number theory',jp:'整数論',icon:'ℕ',color:'lavender',description:'Find the patterns hiding in integers.',lesson:'Prime factors are the building blocks of an integer. For a GCD, take the smallest shared prime exponents; for an LCM, take the largest. If n = pᵃqᵇ, it has (a + 1)(b + 1) positive divisors.',formula:'gcd(a, b) × lcm(a, b) = ab'},
 {id:'algebra',name:'Algebra & quadratics',jp:'式と二次関数',icon:'x²',color:'peach',description:'Make complicated expressions feel simple.',lesson:'Look for a common factor, grouping, or a familiar identity. For a quadratic, completing the square reveals its vertex. On a closed interval, compare the vertex (if inside) with both endpoints.',formula:'ax² + bx + c = a(x + b/2a)² + c − b²/4a'},
 {id:'derivatives',name:'Differentiation',jp:'微分',icon:'ƒ′',color:'blue',description:'Understand slopes, tangents, and change.',lesson:'Differentiate each term using the power rule. A derivative gives the tangent slope at a point. Set f′(x) = 0 to find stationary points, then check how the derivative changes sign.',formula:'d/dx (xⁿ) = nxⁿ⁻¹'},
 {id:'integrals',name:'Integration & area',jp:'積分と面積',icon:'∫',color:'green',description:'Build the whole from its smallest parts.',lesson:'Integration reverses differentiation. For a definite integral, find an antiderivative F and compute F(b) − F(a). For area between curves, integrate the upper function minus the lower, splitting where they cross.',formula:'∫ₐᵇ f(x) dx = F(b) − F(a)'},
 {id:'probability',name:'Counting & probability',jp:'場合の数と確率',icon:'⋮⋮',color:'yellow',description:'Count possibilities. Make uncertainty clearer.',lesson:'Use permutations when order matters and combinations when it does not. For n independent trials with success probability p, the probability of exactly k successes is C(n,k)pᵏ(1−p)ⁿ⁻ᵏ.',formula:'C(n, k) = n! / (k!(n − k)!)'},
 {id:'equations',name:'Integer equations',jp:'整数方程式',icon:'≡',color:'pink',description:'Use divisibility to uncover every solution.',lesson:'For ax + by = c, integer solutions exist exactly when gcd(a,b) divides c. Find one solution, then describe the family. For natural-number solutions, apply positivity constraints to bound the parameter.',formula:'ax + by = c → use factors, remainders, and bounds'}
];
// Selected, translated exercises from the supplied worksheets; originals remain available.
export const problems = [
 ['n1','numbers','Greatest common divisor','Find the greatest common divisor of 90 and 210.','30','Factor both numbers into primes.',['90 = 2 × 3² × 5 and 210 = 2 × 3 × 5 × 7.','Keep the common prime factors with their smallest exponents: 2 × 3 × 5 = 30.'],'1000060778.jpg','1 (1)'],
 ['n2','numbers','Euclidean algorithm','Find the greatest common divisor of 1426 and 1564.','46','Repeatedly divide and keep the remainder.',['1564 = 1426 + 138; 1426 = 10 × 138 + 46.','138 = 3 × 46, so the last nonzero remainder is 46.'],'1000060778.jpg','2'],
 ['n3','numbers','Counting divisors','How many positive divisors does 504 have?','24','First write 504 as a product of prime powers.',['504 = 2³ × 3² × 7.','Choose an exponent for each prime: (3 + 1)(2 + 1)(1 + 1) = 24.'],'1000060778.jpg','3'],
 ['a1','algebra','A quadratic maximum','Find the maximum value of y = −x² + 6x − 4 on −1 ≤ x ≤ 4.','5','Complete the square and locate the vertex.',['y = −(x − 3)² + 5.','The vertex x = 3 is in the interval. The maximum is 5.'],'1000060782.jpg','5 (1)'],
 ['a2','algebra','A quadratic minimum','Find the minimum value of y = −x² + 6x − 4 on −1 ≤ x ≤ 4.','-11','Compare the endpoint values.',['The parabola opens downward, so the minimum is at an endpoint.','y(−1) = −11 and y(4) = 4. The minimum is −11.'],'1000060782.jpg','5 (1)'],
 ['a3','algebra','Factor a quartic','Factor x⁴ − 13x² + 36 completely.','(x+2)(x-2)(x+3)(x-3)','Treat x² as one variable.', ['Let u = x². Then u² − 13u + 36 = (u − 4)(u − 9).','Use the difference of squares twice: (x + 2)(x − 2)(x + 3)(x − 3).'],'1000060782.jpg','1 (3)','self'],
 ['d1','derivatives','The power rule','Differentiate y = 2x³ − 4x + 1.','6x² − 4','Differentiate each term separately.',['The derivative of 2x³ is 6x². The derivative of −4x is −4.','The constant has derivative 0, so y′ = 6x² − 4.'],'1000060777.jpg','1 (1)','self'],
 ['d2','derivatives','Slope of a tangent','For y = x² − x + 2, find the tangent slope at (2, 4).','3','Evaluate the derivative at x = 2.',['y′ = 2x − 1. At x = 2, the slope is 3.','The tangent equation is y − 4 = 3(x − 2), or y = 3x − 2.'],'1000060777.jpg','2'],
 ['d3','derivatives','Stationary points','For y = x³ − 6x² + 9x − 1, what is the local maximum value?','3','Find the zeros of the derivative, then check their signs.',['y′ = 3x² − 12x + 9 = 3(x − 1)(x − 3).','At x = 1, y′ changes from positive to negative, so this is a local maximum.','y(1) = 1 − 6 + 9 − 1 = 3.'],'1000060777.jpg','4'],
 ['i1','integrals','Reverse the power rule','Find the indefinite integral ∫ 6x² dx.','2x³ + C','Increase the exponent by one and divide by the new exponent.',['∫ 6x² dx = 6 × x³/3 + C.','The result is 2x³ + C. Remember the arbitrary constant.'],'1000060777.jpg','14 (1)','self'],
 ['i2','integrals','Area between parabolas','Find the area enclosed by y = x² + 1 and y = −x² + 2x + 4.','7√7 / 3','Find the intersection points and integrate upper minus lower.',['x² + 1 = −x² + 2x + 4 gives x = (1 ± √7)/2.','The difference is −2x² + 2x + 3 = 7/2 − 2(x − 1/2)².','Integrating from (1 − √7)/2 to (1 + √7)/2 gives 7√7/3.'],'1000060780.jpg','5','self'],
 ['i3','integrals','Area between a cubic and a line','Find the area enclosed by y = x³ and y = 3x − 2.','27/4','Factor x³ − 3x + 2 to locate the intersections.',['x³ − 3x + 2 = (x − 1)²(x + 2), so the intersections are x = −2 and x = 1.','On [−2, 1], the cubic lies above the line.','Area = [x⁴/4 − 3x²/2 + 2x] from −2 to 1 = 27/4.'],'1000060780.jpg','6'],
 ['p1','probability','Around the table','In how many ways can 8 distinct people sit around a circular table? Rotations count as the same arrangement.','5040','Fix one person, then arrange everyone else.',['Fix one person to remove rotational duplicates.','Arrange the other 7 people: 7! = 5040. Reflections remain distinct.'],'1000060782.jpg','7 (1)'],
 ['p2','probability','Choosing vertices','How many triangles can be formed from the vertices of a regular decagon?','120','Each choice of 3 vertices gives one triangle.',['No three vertices of a regular decagon are collinear.','C(10, 3) = (10 × 9 × 8)/(3 × 2 × 1) = 120.'],'1000060782.jpg','7 (2)'],
 ['p3','probability','Repeated dice rolls','A fair die is rolled 5 times. What is the probability of getting a multiple of 3 exactly 3 times?','40/243','A success is a 3 or a 6, so p = 1/3.',['Choose which 3 rolls are successes: C(5, 3) = 10.','Multiply: 10 × (1/3)³ × (2/3)² = 40/243.'],'1000060782.jpg','8 (1)'],
 ['e1','equations','Positive integer pairs','How many pairs of positive integers (x, y) satisfy 3x + 5y = 45?','2','Reduce modulo 3 to constrain y.',['Modulo 3, 2y ≡ 0, so y is a multiple of 3.','With x > 0 and y > 0, y can be 3 or 6. The pairs are (10, 3) and (5, 6).'],'1000060779.jpg','11'],
 ['e2','equations','Two remainders','Find the largest three-digit integer that leaves remainder 3 when divided by 6 and remainder 5 when divided by 17.','957','Write n = 6k + 3 and substitute into the other congruence.',['6k + 3 ≡ 5 (mod 17), so 6k ≡ 2 and k ≡ 6 (mod 17).','Thus n = 39 + 102t. The largest three-digit value is 39 + 102 × 9 = 957.'],'1000060779.jpg','13'],
 ['e3','equations','Factor to find integers','Find all positive integer pairs (x, y) satisfying x² − y² + x − y = 10.','(5, 4) and (3, 1)','Factor out x − y.',['(x − y)(x + y + 1) = 10. Both factors are positive.','The factor pair (1, 10) gives x = 5 and y = 4; (2, 5) gives x = 3 and y = 1.','So the positive integer pairs are (5, 4) and (3, 1).'],'1000060779.jpg','14','self']
].map(([id,topic,title,prompt,answer,hint,steps,source,number,mode])=>({id,topic,title,prompt,answer,hint,steps,source,number,mode:mode||'numeric'}));
